export const STUDENT_LOGIN_REQUEST = "STUDENT_LOGIN_REQUEST";
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS";
export const STUDENT_LOGIN_FAIL = "STUDENT_LOGIN_FAIL";

export const GET_RESULTS_REQUEST = "GET_RESULTS_REQUEST";
export const GET_RESULTS_SUCCESS = "GET_RESULTS_SUCCESS";
export const GET_RESULTS_FAIL = "GET_RESULTS_FAIL";

export const STUDENT_LOGOUT = "STUDENT_LOGOUT";
